# Generated by Django 4.2.2 on 2023-07-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=150)),
                ('spell', models.TextField(max_length=500)),
                ('money', models.CharField(max_length=100)),
                ('equipment', models.TextField(max_length=500)),
                ('class_ability', models.TextField(max_length=500)),
                ('hit_dice', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('acrobatics_dex', models.CharField(max_length=100)),
                ('animal_handling_wis', models.CharField(max_length=100)),
                ('arcana_int', models.CharField(max_length=100)),
                ('athletics_str', models.CharField(max_length=100)),
                ('deception_cha', models.CharField(max_length=100)),
                ('history_int', models.CharField(max_length=100)),
                ('insight_wis', models.CharField(max_length=100)),
                ('intimidation_cha', models.CharField(max_length=100)),
                ('investigation_int', models.CharField(max_length=100)),
                ('medicine_wis', models.CharField(max_length=100)),
                ('nature_int', models.CharField(max_length=100)),
                ('perception_wis', models.CharField(max_length=100)),
                ('performance_cha', models.CharField(max_length=100)),
                ('persuasion_cha', models.CharField(max_length=100)),
                ('religion_int', models.CharField(max_length=100)),
                ('sleight_of_hand_dex', models.CharField(max_length=100)),
                ('stealth_dex', models.CharField(max_length=100)),
                ('survival_wis', models.CharField(max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gears', to='main_app.character')),
            ],
        ),
    ]
