# Generated by Django 4.2.2 on 2023-07-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='acrobatics_dex',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='animal_handling_wis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='arcana_int',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='athletics_str',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='class_ability',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='gear',
            name='deception_cha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='equipment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='gear',
            name='history_int',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='hit_dice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='insight_wis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='intimidation_cha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='investigation_int',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='medicine_wis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='money',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='nature_int',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='perception_wis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='performance_cha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='persuasion_cha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='religion_int',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='sleight_of_hand_dex',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='spell',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='gear',
            name='stealth_dex',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='survival_wis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gear',
            name='weapon',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
