# Generated by Django 4.2.2 on 2023-07-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gear',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='main_app.gear'),
        ),
    ]
