# Generated by Django 4.2.2 on 2023-07-15 17:11

from django.db import migrations

def migrate_gear_to_character(apps, schema_editor):
    Character = apps.get_model('main_app', 'Character')
    Gear = apps.get_model('main_app', 'Gear')
    for gear in Gear.objects.all():
        character = gear.character.first()  # Gets the first Character related to the Gear
        if character:
            character.gear = gear
            character.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_campaign'),
    ]

    operations = [
        migrations.RunPython(migrate_gear_to_character)
    ]
