# Generated by Django 4.2.2 on 2023-07-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_character_gear'),
        ('main_app', '0005_auto_20230715_1716'),
    ]

    operations = [
    ]
